Fix 20210203
139bercy/decp-augmente pull request #14
Opened 2021-03-09 09:40 UTC by desrousseaux

2021-03-09 10:09 UTC, strainel requested changes

2021-03-09 10:09 UTC, strainel commented on config.json
> +	"code-insee-postaux-geoflar": "code-insee-postaux-geoflar.csv"
ce fichier là n'est plus nécessaire, il a été remplacé. cf https://github.com/139bercy/decp-augmente/blob/master/config-circleci.json

2021-03-09 10:09 UTC, strainel commented on config.json.example
> +	"code-insee-postaux-geoflar": "code-insee-postaux-geoflar.csv"
idem remarque précédente

2021-03-09 13:51 UTC, QMaire commented on nettoyage.py
> +    df["montant"] = df["montant"].apply(lambda x: 0 if is_false_amount(x) else x)
Ne fonctionne pas en l'état à cause du format de la colonne "montant". 
Les valeurs vides ne sont pas prises en compte (4898)

2021-03-09 14:06 UTC, QMaire commented on nettoyage.py
> +    df["montant"] = df["montant"].apply(lambda x: 0 if is_false_amount(x) else x)
Je ne connais pas le mode de remplissage de la variable "montant". Cependant, si il est possible qu ne valeur soit vide, alors cette ligne renvoie une erreur

2021-03-23 19:51 UTC, QMaire approved these changes

2021-03-24 08:24 UTC, loldebyte commented on nettoyage.py
> +    try: #le try/except permet de prendre en compte les lignes ou le montant n'est pas renseigné. Dans ce cas, le montant sera considéré comme faux.
Ne serait-il pas moins gourmand de "boucher" les montants non-renseignés au préalable ?
Remplacer des NaN par des 0 affecte les moyennes etc... mais si vous effectuiez ces opérations elles planteraient en tombant sur les NaN, non ? cf [df.fillna()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html)

2021-03-24 08:24 UTC, loldebyte commented on nettoyage.py
> +    df["montant"] = df["montant"].apply(lambda x: 0 if is_false_amount(x) else x)
Ok alors clairement, si c'est ça l'objectif il faut faire un fillna au préalable, je pense.

2021-03-24 08:24 UTC, loldebyte commented on nettoyage.py
> +    #df['montant'] = np.where(df['montant'] == 0, np.NaN, df['montant'])
```suggestion
    # df.fillna(0, inplace=True)
```

2021-03-24 11:10 UTC, merged