Ajout Luhn-typeEtablissement
139bercy/decp-augmente pull request #15
Opened 2021-03-12 10:53 UTC by QMaire

4 changements ont été faits :

- Modification de l'ordre des colonnes
- Modification de certains noms de colonnes
- Ajout du type de l'entreprise dans la base (ainsi que l'jaout de la base dans les différentes config)
- Modification de la fonction Luhn pour la rendre plus générale (Applicable au Siret aussi) et application de cette dernière pour data_augmente

2021-03-12 11:12 UTC, strainel commented
à mon avis, il faut changer de manière de faire & passer par un fork préalable, car en l'état ca ne prend pas en compte sur circleci une *vraie* PR.

2021-03-12 14:47 UTC, desrousseaux requested changes

2021-03-12 14:47 UTC, desrousseaux commented on enrichissement.py
> +    to_add = pd.read_csv(path, usecols = ["siren", "categorieEntreprise", "nicSiegeUniteLegale"])
base_type_entreprise, stock_unite_legale, plus explicite le nom :)

2021-03-12 14:47 UTC, desrousseaux commented on enrichissement.py
> +        return df
sortir le merge et le return du try except

2021-03-12 14:47 UTC, desrousseaux commented on enrichissement.py
> +    return df
Je n'ai pas compris le fonctionnement de ce code.

2021-03-12 14:47 UTC, desrousseaux commented on enrichissement.py
> +        chiffres = pd.DataFrame(map(int, list(str(nbentier))), columns=['Number_list'])
une liste serait plus adaptee qu'un dataframe

2021-03-12 14:47 UTC, desrousseaux commented on enrichissement.py
> +        chiffres = pd.DataFrame(map(int, list(str(nbentier))), columns=['Number_list'])
Je suggere ce code, un peu plus court :
def is_luhn_valid(x):
    luhn_corr = [0,2,4,6,8,1,3,5,7,9]
    l = [int(i) for i in list(str(x))]
    l2 = [luhn_corr[i] if (index+1) % 2 == 0 else i for index, i in enumerate(l[::-1])]
    return sum(l2) % 10 == 0

2021-03-12 14:47 UTC, desrousseaux commented on nettoyage.py
> +def Check_files(conf):
Le snake case ne prend pas de majuscule. Pour le nom, je suggere check_reference_files

2021-03-12 14:47 UTC, desrousseaux commented on nettoyage.py
> +           os.path.exists(os.path.join(path, type_entreprise))
On pourrait boucler sur les fichiers dans le json non ?

2021-03-12 14:47 UTC, desrousseaux commented on nettoyage.py
> +           os.path.exists(os.path.join(path, type_entreprise))
Et dans la boucle, si non trouve, raise une erreur avec le nom du fichier manquant.

2021-03-12 14:47 UTC, desrousseaux commented on nettoyage.py
> +        return True
Il n'y a pas besoin de retourner qch.

2021-03-12 14:47 UTC, desrousseaux commented on nettoyage.py
> +    if Check_files(conf):
Pas besoin du if

2021-03-12 15:01 UTC, QMaire commented on enrichissement.py
> +    return df
Avec le Df de travail j ai remarqué qu'il y avait plusieurs fois la colonne siretEtablissement. 
ce petit bout de code me permet de supprimer toutes les colonnes  sous ce nom et n'en garder qu'une.

Je vais ajouter des commentaires

2021-03-12 15:02 UTC, desrousseaux commented on enrichissement.py
> +        df = suppression_Siret_doublon(df)
On veut appliquer le dedoublonnage au dataframe du referentiel non ?

2021-03-15 10:54 UTC, loldebyte reviewed
Commentaires génériques sur le style puisque je suis trop peu familier avec le projet pour être critique à ce sujet

2021-03-15 10:54 UTC, loldebyte commented on enrichissement.py
> +    return df
Ce serait beaucoup plus clair IMHO de passer par une variable intermédiaire dans le genre :
```suggestion
    columns_to_keep = [col1, col2,  ...]
    df = df[cols]
    return df
```

2021-03-15 10:54 UTC, loldebyte commented on enrichissement.py
> +    return df
Idéalement, passer une conf, ou peut être une "constante" définie au début du script ?

2021-03-15 10:54 UTC, loldebyte commented on enrichissement.py
> +    refCPV = pd.read_excel(path, usecols=['CODE', 'FR'], engine='openpyxl')
Pas nécessaire avec pandas >=1.2 cf [release notes](https://pandas.pydata.org/docs/whatsnew/v1.2.0.html)
Mais par contre il faudrait modifier le `requirements.txt` pour exprimer cette dépendance :
```
    pandas>=1.2.0
```

2021-03-15 10:54 UTC, loldebyte commented on main.py
> +print((t2-t1)/60)
Finir le script avec une newline :
```suggestion
print((t2-t1)/60)

```

2021-03-15 10:54 UTC, loldebyte commented on nettoyage.py
>      main()
```suggestion
    main()

```

2021-03-18 10:06 UTC, desrousseaux approved these changes

2021-03-23 08:52 UTC, loldebyte approved these changes
PEP8/8

2021-03-23 08:52 UTC, loldebyte commented on enrichissement.py
>          return False
Peut être qu'utiliser la librairie [luhn](https://github.com/mmcloughlin/luhn/blob/master/luhn.py) (ou copier son code) serait plus efficace (et/ou épargnerait un try/except) ?

2021-03-23 15:10 UTC, QMaire commented on enrichissement.py
>          return False
Après essai, même si la librairie permet d'obtenir une réponse plus rapide, elle ne prend pas en compte le cas particulier de La Poste. On devrait donc garder la seconde vérification.

2021-03-23 15:35 UTC, merged