Ajout accord cadre V2
139bercy/decp-augmente pull request #27
Opened 2021-04-09 07:27 UTC by QMaire

Refonte de la fonction Detection Accord Cadre

2021-04-09 12:21 UTC, loldebyte commented on enrichissement.py
> +    return df_final
pd.concat(liste_dataframe) fait la même chose, et probablement plus rapidement.

2021-04-09 12:49 UTC, loldebyte requested changes
Utiliser les list comprehension ça représente un vrai gros gain de temps, le reste c'est plutôt annexe

2021-04-09 12:49 UTC, loldebyte commented on enrichissement.py
> +    return df_final
pd.concat(liste_dataframe) fait la même chose, et probablement plus rapidement.

2021-04-09 12:49 UTC, loldebyte commented on enrichissement.py
> +    return liste_dataframe
un dictionnaire avec pour clé les années serait peut être plus pratique ?

2021-04-09 12:49 UTC, loldebyte commented on enrichissement.py
> +def subset_dataframe_annee(df):
le nom est un peu trompeur, on s'attend à récupérer un dataframe

2021-04-09 12:49 UTC, loldebyte commented on enrichissement.py
> +    return liste_dataframe
Sinon utiliser une list comprehension :
```suggestion
   return [dataframe_annee = df[df.anneeNotification == annee]
              for annee in np.unique(df.anneeNotification)]:
        
```

2021-04-09 12:49 UTC, loldebyte commented on enrichissement.py
> +            dataframe_mois[i]["accord-cadrePresume"] = ""
utiliser un dictionnaire serait plus explicite ici, sinon utiliser [map](https://book.pythontips.com/en/latest/map_filter.html#map), mais ça demanderait de réécrire `subset_dataframe_annee` et `subset_dataframe_dec_jan` donc pas sur que ce soit une bonne idée.

2021-04-12 12:33 UTC, QMaire commented on enrichissement.py
> +    return liste_dataframe
Par pure curiosité, est ce que cette syntaxe à un impact sur le coût de la fonction ? (aussi bien en mémoire qu'en temps ?)

2021-04-16 14:41 UTC, merged