Add feature modifications
139bercy/decp-augmente pull request #46
Opened 2021-07-06 13:32 UTC by QMaire

2021-07-06 13:34 UTC, QMaire commented on enrichissement.py
> +    df = df.reindex(columns=['id', "id_source", 'idMarche', 'source', 'type', 'natureObjetMarche', 'objetMarche', 'codeCPV_Original', 'codeCPV', "codeCPV_division",
id a été modifié 
id_source correspond aux identifiants en provenance de decp.json, notre source initiale

2021-07-21 12:21 UTC, desrousseaux reviewed
J'ai commencé à lire le code mais je ne comprends pas pourquoi on travaille sur le json plutôt que sur df.

2021-07-21 12:21 UTC, desrousseaux commented on nettoyage.py
> +    return L_indice
return data["marches"] ["modifications"] > 0
plutôt non ?

2021-09-01 06:49 UTC, QMaire commented
Dans le json, la clef modifications est structuré d'une certaine facon ( [Dictionnaire] ). Lorsque l'on utilise json.normalize pour passer de json à df, ce format n'est pas converti correctement (et je suppose que c'est la raison pour laquelle modification n'avait pas été pris en compte).

2021-09-01 13:32 UTC, loldebyte requested changes

2021-09-01 13:32 UTC, loldebyte commented on nettoyage.py
> +        - Le second contiendra l'ensemble des lignes correspondant au marché isolé dans le df1 qui ont pour objet modalite"""
définir les paramètres pris en arguments par la fonction et le type de retour:
```suggestion
    """Définition de deux dataFrame.
        - Le premier qui contiendra uniquement les lignes avec modification, pour le marché ayant pour objet modalite
        - Le second contiendra l'ensemble des lignes correspondant au marché isolé dans le df1 qui ont pour objet modalite
        
:param df: la source totale des données ?
:param sub_data: le sous-ensemble correspondant à ...
:param modalite: la modalité sur laquelle on veut filtrer
:return: un tuple (premier_df, second_df)
"""
```
Au passage on note que les `"""` qui ferment une docstring sont sur une ligne a part, cf tu l'as deviné, le sacro-saint [pep8](https://www.python.org/dev/peps/pep-0008/#documentation-strings)!

2021-09-01 13:32 UTC, loldebyte commented on nettoyage.py
> +    """ Permet de fusionner les colonnes xxxModification et sa colonne """
Préciser quoi passer dans les paramètres de la fonction : `raw: un <type> contenant <ce que c'est sensé représenter>`

2021-09-01 13:32 UTC, loldebyte commented on nettoyage.py
> +        return df_source
Dans ce cas là, vu que c'est simple, c'est probablement OK de modifier inplace et renvoyer, mais il faudrait le préciser dans la docstring

2021-09-01 13:32 UTC, loldebyte commented on nettoyage.py
> +    En sortie: idMarche correspondra à un identifiant unique pour toutes les lignes composants un marché SI il a eu une modification"""
Je suppose que `df` est le dataframe renvoyé par `prise_en_compte_modifications` et `dict_modification` le dictionnaire renvoyé par `recuperation_colonne_a_modifier`. Préciser les arguments ne ferait jamais de mal, mais si ce que j'ai supposé ici est faux c'est **impératif**.

2021-09-01 13:32 UTC, loldebyte commented on nettoyage.py
> +            marche_init = fusion_source_modification(raw, marche_init, col_modification, dict_modification)
```suggestion
            marche_init = fusion_source_modification(raw, marche_init, dict_modification.keys(), dict_modification)
```
Ne pas passer par une variable intermédiaire est ici plus explicite.

2021-09-01 13:32 UTC, loldebyte commented on nettoyage.py
> +        marche_init["idtech"] = marche.iloc[-1].id_technique
Pourquoi on récupère l'id_technique du dernier marché ?

2021-09-01 13:32 UTC, loldebyte commented on nettoyage.py
> +            marche_init = fusion_source_modification(raw, marche_init, col_modification, dict_modification)
Pourquoi pas :
```suggestion
        for j in marche:
            raw = marche.iloc[j]
            marche_init = fusion_source_modification(raw, marche_init, col_modification, dict_modification)
```

2021-09-01 13:32 UTC, loldebyte commented on nettoyage.py
> +        df_to_concatene = pd.concat([df_to_concatene, marche_init], copy = False)
```suggestion
        df_to_concatene = pd.concat([pd.DataFrame(), marche_init], copy = False)
```
Et supprimer la première définition de la variable, ça encombre pour pas grand chose IMO

2021-09-01 13:32 UTC, loldebyte commented on nettoyage.py
> +    return df
Si tu tiens au comportement inplace + return, précise bien que ça modifie inplace dans la docstring pour éviter les confusions éventuelles

2021-09-01 15:42 UTC, QMaire commented on nettoyage.py
> +        if len(data["marches"][i]["modifications"]) > 0:
Je ne savais pas ! 
Changement fait !

2021-09-02 08:10 UTC, QMaire commented on nettoyage.py
> +    En sortie: idMarche correspondra à un identifiant unique pour toutes les lignes composants un marché SI il a eu une modification"""
JE vais faire une PR avec toute la refonte des docstrings

2021-09-02 09:39 UTC, loldebyte approved these changes
Impeccable, j'ai rien à redire :)

2021-09-03 08:06 UTC, merged