V2 augmente fix
139bercy/decp-augmente pull request #62
Opened 2022-10-21 12:24 UTC by HGInfoNancy

Fix de augmenté v2 pour que ça tourne en local

2022-10-21 12:51 UTC, desrousseaux requested changes

2022-10-21 12:51 UTC, desrousseaux commented on .github/workflows/main.yml
> +    branches:
enlever le github workflow, remettre le fichier circleci.

2022-10-21 12:51 UTC, desrousseaux commented on get-data-daily.sh
> -ls
??

2022-10-21 12:51 UTC, desrousseaux commented on main.py
> +    nettoyage.main() # debug
remove

2022-10-21 12:51 UTC, desrousseaux commented on nettoyage.py
> +pd.options.mode.chained_assignment = None  # default='warn'
Pourquoi ?

2022-10-21 12:51 UTC, desrousseaux commented on nettoyage.py
> +    if conf_debug["subset"] :
ce paragraphe ne sera que pour du debug donc -> if debug: ...

2022-10-21 12:51 UTC, desrousseaux commented on nettoyage.py
>      """
global conf_data ?

2022-10-21 12:51 UTC, desrousseaux commented on nettoyage.py
> +    l_key_useless = ["path_to_project", "path_to_data"]
l_key_useless -> useless_keys

2022-10-21 12:51 UTC, desrousseaux commented on nettoyage.py
> +                f"Remplacé par l'identifiatn de l'autorité Concedante")
typo indentifiant, condédante

2022-10-21 12:51 UTC, desrousseaux commented on nettoyage.py
> +    donnees_inutiles = ['dateSignature', 'dateDebutExecution', 'valeurGlobale', 'donneesExecution', 'concessionnaires',
-> useless_columns

2022-10-21 12:51 UTC, desrousseaux commented on nettoyage.py
> +    df = df[~(df['titulaires'].isna())]
??

2022-10-21 12:51 UTC, desrousseaux commented on nettoyage.py
> +    On cherche à vérifier si les parties entières des montants sont composés d'au moins 5 threshold fois le meme chiffre
composées typo

2022-10-21 12:51 UTC, desrousseaux commented on nettoyage.py
> +        nb_montant_calcul_egal_zero = 0
essayer d'enlever try except

2022-10-21 13:03 UTC, HGInfoNancy commented on .github/workflows/main.yml
> +    branches:
OK

2022-10-21 13:17 UTC, HGInfoNancy commented on get-data-daily.sh
> -ls
Dans son workflow il ne télécharge pas quotidiennement le decp. Sûrement par soucis de practicité, mais ça n'a pas de raison d'avoir été retiré. Je le remets.

2022-10-21 13:24 UTC, HGInfoNancy commented on nettoyage.py
>      """
oui

2022-10-21 13:27 UTC, HGInfoNancy commented on nettoyage.py
> +                f"Remplacé par l'identifiatn de l'autorité Concedante")
condédante ?

2022-10-21 14:34 UTC, HGInfoNancy commented on nettoyage.py
> +    df = df[~(df['titulaires'].isna())]
A voir plus tard

2022-10-21 15:15 UTC, HGInfoNancy commented on nettoyage.py
> +    df['dureeMois'] = df['dureeMois'].astype(np.int64)
Non, pour une écriture scientifique propre c'est un float donc faut refaire un typage là mtn

2022-10-26 12:18 UTC, desrousseaux approved these changes

2022-10-27 11:11 UTC, kaa-serpent commented
La ci fonctionne, mais une partie du script de nettoyage est omis

2022-10-28 08:20 UTC, desrousseaux reviewed
enlever le notebook de l'index

2022-10-28 08:57 UTC, merged